### ISSUE TITLE
qrimage

### ISSUE THREAD

**Issue by borisdaeppen** [frithnanth/perl6-Image-QRCode#2]
Hi,

in the examples, you show how to render the data structure into a png file.
imho it would be good to offer this as a method in the module directly.
is there a reason (other than time/effort) you decided not to include such a method?
could you add such a method?

I'm asking because I'm currently doing some training material for Perl beginners.
I made am example application in Perl 5: https://gitlab.com/borisdaeppen/Perl-Training

It is a simple web QRCode generator using Mojolicious and Imager::QRCode.
Now I am looking if I could do an equivalent example application in Perl 6.
It would be my first Perl 6 code ever though...

Anyways, thanks a lot for your module!

**Comment by frithnanth** [comment]
Hi,

I didn't want to add a dependence to this module, since there isn't a module (or a set of modules) which might provide a consistent interface to at least the most used image formats.
I added an example to show how to save an "inflated" PNG, since there's not even an interface to the JPEG or GIF formats. There's another module able to generate PNG files, but its interface provides only a method to set a single pixel, so even if it has its use, in this context its interface would be atrocious.
I will certainly add a method whenever I'll find (or write :-) a module able to write the most common image formats.

Thank you for using my module!
